export const GLOBAL = {
  TOKEN: {
    UPDATE: 'GLOBAL.TOKEN.UPDATE',
    REMOVE: 'GLOBAL.TOKEN.REMOVE',
  },

  USER: {
    UPDATE: 'GLOBAL.USER.UPDATE',
  },

  MENUS: {
    UPDATE: 'GLOBAL.MENUS.UPDATE',
  },

  LOADING: {
    SHOW: 'GLOBAL.IS_LOADING.SHOW',
    HIDE: 'GLOBAL.IS_LOADING.HIDE',
  },

  LOGIN: 'GLOBAL.LOGIN',
  LOGOUT: 'GLOBAL.LOGOUT',
}

export const SYSTEM = {
  FORM_LOADING: {
    UPDATE: 'SYSTEM.FORM_LOADING.UPDATE',
  },

  DEPARTMENT: {
    READ: 'SYSTEM.DEPARTMENT.READ',
    CREATE: 'SYSTEM.DEPARTMENT.CREATE',
    UPDATE: 'SYSTEM.DEPARTMENT.UPDATE',
    REMOVE: 'SYSTEM.DEPARTMENT.REMOVE',
  },
}

export const BIZ = {
  INIT: 'BIZ.INIT',
  CREATE: 'BIZ.CREATE',
  UPDATE: 'BIZ.UPDATE',
  DELETE: 'BIZ.DELETE',
  ROUTE: 'BIZ.ROUTE',
  EDIT: 'BIZ.EDIT',
}
