export default {
  total: 23,
  per_page: 10,
  current_page: 1,
  last_page: 1,
  next_page_url: null,
  prev_page_url: null,
  from: 1,
  to: 10,
  data: [
    {
      id: 11,
      number: '150414891263',
      from_name: '来自xxx',
      content: '题目内容哦哦哦哦哦',
      question_status: 1,
      user_id: 22,
      user_realname: 'admin管理员',
      question_type_name: '选择题',
      question_difficulty_name: '容易',
      paper_type_name: '历年真题',
      year_name: '2017',
      question_status_name: '草稿',
    },
    {
      id: 11,
      number: '150414891263',
      from_name: '来自xxx',
      content: '题目内容哦哦哦哦哦',
      question_status: 1,
      user_id: 22,
      user_realname: 'admin管理员',
      question_type_name: '选择题',
      question_difficulty_name: '容易',
      paper_type_name: '历年真题',
      year_name: '2017',
      question_status_name: '草稿',
    },
    {
      id: 11,
      number: '150414891263',
      from_name: '来自xxx',
      content: '题目内容哦哦哦哦哦',
      question_status: 1,
      user_id: 22,
      user_realname: 'admin管理员',
      question_type_name: '选择题',
      question_difficulty_name: '容易',
      paper_type_name: '历年真题',
      year_name: '2017',
      question_status_name: '草稿',
    },
    {
      id: 11,
      number: '150414891263',
      from_name: '来自xxx',
      content: '题目内容哦哦哦哦哦',
      question_status: 1,
      user_id: 22,
      user_realname: 'admin管理员',
      question_type_name: '选择题',
      question_difficulty_name: '容易',
      paper_type_name: '历年真题',
      year_name: '2017',
      question_status_name: '草稿',
    },
    {
      id: 11,
      number: '150414891263',
      from_name: '来自xxx',
      content: '题目内容哦哦哦哦哦',
      question_status: 1,
      user_id: 22,
      user_realname: 'admin管理员',
      question_type_name: '选择题',
      question_difficulty_name: '容易',
      paper_type_name: '历年真题',
      year_name: '2017',
      question_status_name: '草稿',
    },
  ],
}
